### ISSUE TITLE
`System.MissingMethodException` with SpacetimeDB.ClientSDK v1.1.5 (not an issue in v1.1.1)

### ISSUE THREAD

**Issue by joshsmithxrm** [clockworklabs/com.clockworklabs.spacetimedbsdk#321]
When using version 1.1.5 of the `SpacetimeDB.ClientSDK` NuGet package, our C# client application fails with a `System.MissingMethodException`. Downgrading to v1.1.1 resolves the issue. This suggests a regression or breaking change introduced in v1.1.5.

**To Reproduce**
1. Create a C# project.
2. Add the `SpacetimeDB.ClientSDK` NuGet package, version 1.1.5.
3. Implement a basic SpacetimeDB client such as quickstart-chat.
4. Run the client application.
5. Observe the `System.MissingMethodException`.

**Expected behavior**
The client should connect and operate without a `System.MissingMethodException`, as it does with v1.1.1.

**Actual behavior**
The application crashes with a `System.MissingMethodException`.

**Console Output**
vscode ➜ /workspaces/G4 (chat-app-quickstart) $ dotnet run --project /workspaces/G4/quickstart-chat/client/client.csproj
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'System.Object SpacetimeDB.BSATN.IStructuralReadWrite.GetSerializer()'.
   at SpacetimeDB.DbConnectionBase`3..ctor()
   at SpacetimeDB.Types.DbConnection..ctor() in /workspaces/G4/quickstart-chat/client/module_bindings/SpacetimeDBClient.g.cs:line 460
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at SpacetimeDB.DbConnectionBuilder`1..ctor()
   at SpacetimeDB.DbConnectionBase`3.Builder()
   at Program.<>c__DisplayClass0_0.<<Main>$>g__ConnectToDB|1() in /workspaces/G4/quickstart-chat/client/Program.cs:line 46

**Additional context**
- The issue started occurring immediately after updating from `SpacetimeDB.ClientSDK` v1.1.1 to v1.1.5.
- The server-side module is written in C# and published to a local SpacetimeDB instance.
- Issue was reproduced by merely applying all of the steps in the docs for quickstart-chat.

**Environment:**
- OS: Debian GNU/Linux 12 (bookworm) (in VS Code Dev Container)
- .NET Version: net8.0
- SpacetimeDB.ClientSDK Version: 1.1.5
- SpacetimeDB CLI Version: 1.2
- `SpacetimeDB.BSATN.Runtime.dll` version: 1.1.1

**Comment by bfops** [comment]
Thank you for reporting this! We missed publishing some NuGet packages during our release. It will be fixed soon.

**Comment by bfops** [comment]
This should now be fixed. You may have to clear your downloaded packages and possibly your NuGet cache (`dotnet nuget locals --clear all`).

**Comment by joshsmithxrm** [comment]
> This should now be fixed. You may have to clear your downloaded packages and possibly your NuGet cache (`dotnet nuget locals --clear all`).

I performed a dotnet nuget locals --clear all and built the project, I'm still seeing failures, All I did was switch the project from 1.1.1 to 1.1.5 and I'm seeing the failures. Is there any other troubleshooting I should be attempting? 

Here is the project.assets.json
`{
  "version": 3,
  "targets": {
    "net8.0": {
      "SpacetimeDB.BSATN.Runtime/1.1.1": {
        "type": "package",
        "compile": {
          "lib/net8.0/SpacetimeDB.BSATN.Runtime.dll": {
            "related": ".xml"
          }
        },
        "runtime": {
          "lib/net8.0/SpacetimeDB.BSATN.Runtime.dll": {
            "related": ".xml"
          }
        }
      },
      "SpacetimeDB.ClientSDK/1.1.5": {
        "type": "package",
        "dependencies": {
          "SpacetimeDB.BSATN.Runtime": "1.1.1"
        },
        "compile": {
          "lib/netstandard2.1/SpacetimeDB.ClientSDK.dll": {}
        },
        "runtime": {
          "lib/netstandard2.1/SpacetimeDB.ClientSDK.dll": {}
        }
      }
    }
  },
  "libraries": {
    "SpacetimeDB.BSATN.Runtime/1.1.1": {
      "sha512": "ImBHBd2CVBheQOpPCxQJ3GdFUHURe7I5ElpY9U+hCNTackM4hEvJBRD/cfU+EbPUFJJ2Ys9FpFNztKC1eHsnpw==",
      "type": "package",
      "path": "spacetimedb.bsatn.runtime/1.1.1",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "LICENSE",
        "README.md",
        "analyzers/dotnet/cs/SpacetimeDB.BSATN.Codegen.dll",
        "lib/net8.0/SpacetimeDB.BSATN.Runtime.dll",
        "lib/net8.0/SpacetimeDB.BSATN.Runtime.xml",
        "lib/netstandard2.1/SpacetimeDB.BSATN.Runtime.dll",
        "lib/netstandard2.1/SpacetimeDB.BSATN.Runtime.xml",
        "logo.png",
        "spacetimedb.bsatn.runtime.1.1.1.nupkg.sha512",
        "spacetimedb.bsatn.runtime.nuspec"
      ]
    },
    "SpacetimeDB.ClientSDK/1.1.5": {
      "sha512": "nzPCi0cBnf1YfS2W0tIvo1jmUcqVhmfqjbtJq+dyAOM+4oTO7Evfqm6xLXDGSa4ee9cOWx2e3vW8OoDG1JRvYg==",
      "type": "package",
      "path": "spacetimedb.clientsdk/1.1.5",
      "files": [
        ".nupkg.metadata",
        ".signature.p7s",
        "README.md",
        "lib/netstandard2.1/SpacetimeDB.ClientSDK.dll",
        "logo.png",
        "spacetimedb.clientsdk.1.1.5.nupkg.sha512",
        "spacetimedb.clientsdk.nuspec"
      ]
    }
  },
  "projectFileDependencyGroups": {
    "net8.0": [
      "SpacetimeDB.ClientSDK >= 1.1.5"
    ]
  },
  "packageFolders": {
    "/home/vscode/.nuget/packages/": {}
  },
  "project": {
    "version": "1.0.0",
    "restore": {
      "projectUniqueName": "/workspaces/G4/quickstart-chat/client/client.csproj",
      "projectName": "client",
      "projectPath": "/workspaces/G4/quickstart-chat/client/client.csproj",
      "packagesPath": "/home/vscode/.nuget/packages/",
      "outputPath": "/workspaces/G4/quickstart-chat/client/obj/",
      "projectStyle": "PackageReference",
      "configFilePaths": [
        "/home/vscode/.nuget/NuGet/NuGet.Config"
      ],
      "originalTargetFrameworks": [
        "net8.0"
      ],
      "sources": {
        "https://api.nuget.org/v3/index.json": {}
      },
      "frameworks": {
        "net8.0": {
          "targetAlias": "net8.0",
          "projectReferences": {}
        }
      },
      "warningProperties": {
        "warnAsError": [
          "NU1605"
        ]
      },
      "restoreAuditProperties": {
        "enableAudit": "true",
        "auditLevel": "low",
        "auditMode": "direct"
      }
    },
    "frameworks": {
      "net8.0": {
        "targetAlias": "net8.0",
        "dependencies": {
          "SpacetimeDB.ClientSDK": {
            "target": "Package",
            "version": "[1.1.5, )"
          }
        },
        "imports": [
          "net461",
          "net462",
          "net47",
          "net471",
          "net472",
          "net48",
          "net481"
        ],
        "assetTargetFallback": true,
        "warn": true,
        "frameworkReferences": {
          "Microsoft.NETCore.App": {
            "privateAssets": "all"
          }
        },
        "runtimeIdentifierGraphPath": "/usr/share/dotnet/sdk/8.0.408/PortableRuntimeIdentifierGraph.json"
      }
    }
  }
}`

Switching back to 1.1.1 immediately resolved the issue again.

**Comment by bfops** [comment]
@JoshSmithXRM I can just say that we pushed `SpacetimeDB.BSATN.Runtime` and `SpacetimeDB.Runtime` to 1.1.2, and it looks like you're still getting the old ones. I'm not totally sure what other caches etc need clearing unfortunately.

**Comment by joshsmithxrm** [comment]
> [@JoshSmithXRM](https://github.com/JoshSmithXRM) I can just say that we pushed `SpacetimeDB.BSATN.Runtime` and `SpacetimeDB.Runtime` to 1.1.2, and it looks like you're still getting the old ones. I'm not totally sure what other caches etc need clearing unfortunately.

@bfops appreciate the feedback, I'm just getting into SpacetimeDB so I haven't played with it too much focusing on learning the core behind it first. Will let you know if I figure out a workaround it's not super urgent for me to get my client to 1.1.5 right now as far as I can tell. Looks like everything is working fine. Thanks for the quick responses, it is appreciated!

**Comment by joshsmithxrm** [comment]
Actually, it looks like I was able to get through the issue. It looks like the default server project references v 1.1.* I forced the server project to 1.1.2. I rebuilt my container and I was able to publish the server and run the client without any issues. I'm not sure if the 1.1.* was the issue or not or if it got resolved because I rebuilt my dev container but, it appears to be working at this time.

Thanks for the help with this one, I think this is solved as far as I can tell.

**Comment by bfops** [comment]
Excellent! Thanks for following up!
